# Generated by Django 6.0.3 on 2026-04-13 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
        migrations.RemoveConstraint(
            model_name='chapterprogress',
            name='unique_user_chapter_progress',
        ),
        migrations.RemoveConstraint(
            model_name='courseenrollment',
            name='unique_user_course_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='lessonprogress',
            name='unique_user_lesson_progress',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.JSONField(blank=True, help_text='Optional multilingual description', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='', help_text="Course code (e.g., 'park-guide-101')", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Is this course available for enrollment?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Courses that must be completed first', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Course thumbnail image URL', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.JSONField(help_text='Multilingual title {en, ms, zh}'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_images',
            field=models.JSONField(default=list, help_text='List of image URLs'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_text',
            field=models.JSONField(blank=True, help_text='Multilingual markdown/HTML content', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_videos',
            field=models.JSONField(default=list, help_text='List of {url, title, description}'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_time',
            field=models.PositiveIntegerField(default=10, help_text='Estimated reading time in minutes'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within chapter'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.JSONField(help_text='Multilingual lesson title'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Time spent in seconds'),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='practiceattempt',
            name='answers',
            field=models.JSONField(help_text="User's answers {question_idx: selected_answer}"),
        ),
        migrations.AlterField(
            model_name='practiceexercise',
            name='questions',
            field=models.JSONField(help_text='Array of {type, question, options, correct_answer, explanation}'),
        ),
        migrations.AlterField(
            model_name='practiceexercise',
            name='title',
            field=models.JSONField(help_text='Multilingual practice title'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.JSONField(help_text='Array of {type, question, options, correct_answer, explanation}'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='show_answers',
            field=models.BooleanField(default=True, help_text='Show correct answers after submission?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='Time limit in minutes, none if null', null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.JSONField(help_text='Multilingual quiz title'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(help_text="User's answers {question_idx: selected_answer}"),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Time spent in seconds'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='chapterprogress',
            unique_together={('user', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('chapter', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='practiceexercise',
            unique_together={('chapter', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('chapter', 'order')},
        ),
        migrations.AddIndex(
            model_name='practiceattempt',
            index=models.Index(fields=['user', 'exercise'], name='courses_pra_user_id_019120_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz'], name='courses_qui_user_id_a704a3_idx'),
        ),
    ]
