# Generated by Django 6.0.3 on 2026-04-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text="Course code (e.g., 'park-guide-101')", max_length=50),
        ),
    ]
