# Generated by Django 6.0.3 on 2026-04-14 01:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_improve_progress_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterprogress',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='practiceattempt',
            name='courses_pra_user_id_exercise_idx',
        ),
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='courses_qui_user_id_quiz_idx',
        ),
        migrations.RenameIndex(
            model_name='chapterprogress',
            new_name='courses_cha_user_id_fd1551_idx',
            old_name='courses_cha_user_id_complete_idx',
        ),
        migrations.RenameIndex(
            model_name='chapterprogress',
            new_name='courses_cha_user_id_081f4e_idx',
            old_name='courses_cha_user_id_chapter_idx',
        ),
        migrations.RenameIndex(
            model_name='chapterprogress',
            new_name='courses_cha_complet_a95bc9_idx',
            old_name='courses_cha_complet_at_idx',
        ),
        migrations.RenameIndex(
            model_name='courseenrollment',
            new_name='courses_cou_user_id_e553f2_idx',
            old_name='courses_cou_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='courseenrollment',
            new_name='courses_cou_user_id_147840_idx',
            old_name='courses_cou_user_id_course_idx',
        ),
        migrations.RenameIndex(
            model_name='courseenrollment',
            new_name='courses_cou_status_126984_idx',
            old_name='courses_cou_status_idx',
        ),
        migrations.RenameIndex(
            model_name='courseenrollment',
            new_name='courses_cou_complet_80598f_idx',
            old_name='courses_cou_complet_date_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonprogress',
            new_name='courses_les_user_id_505409_idx',
            old_name='courses_les_user_id_completed_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonprogress',
            new_name='courses_les_user_id_83b81f_idx',
            old_name='courses_les_user_id_lesson_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonprogress',
            new_name='courses_les_complet_e741c2_idx',
            old_name='courses_les_complet_at_idx',
        ),
        migrations.RenameIndex(
            model_name='practiceattempt',
            new_name='courses_pra_user_id_c8beec_idx',
            old_name='courses_pra_user_id_passed_idx',
        ),
        migrations.RenameIndex(
            model_name='practiceattempt',
            new_name='courses_pra_complet_8e335d_idx',
            old_name='courses_pra_complet_at_idx',
        ),
        migrations.RenameIndex(
            model_name='quizattempt',
            new_name='courses_qui_user_id_44fa76_idx',
            old_name='courses_qui_user_id_passed_idx',
        ),
        migrations.RenameIndex(
            model_name='quizattempt',
            new_name='courses_qui_complet_b38500_idx',
            old_name='courses_qui_complet_at_idx',
        ),
        migrations.AlterField(
            model_name='chapterprogress',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.chapter'),
        ),
        migrations.AlterField(
            model_name='chapterprogress',
            name='practice_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chapterprogress',
            name='progress_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chapterprogress',
            name='quiz_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chapterprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='practiceattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
