# Generated by Django 6.0.3 on 2026-05-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RangerEyeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=120)),
                ('device_id', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='ranger_eye/uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RangerEyeRecorderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
                ('last_recording', models.CharField(blank=True, default='None yet', max_length=255)),
                ('next_recording', models.CharField(blank=True, default='Starting soon', max_length=255)),
                ('message', models.TextField(blank=True, default='Video recorder starting...')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RangerEye Recorder Status',
                'verbose_name_plural': 'RangerEye Recorder Status',
            },
        ),
        migrations.CreateModel(
            name='RangerEyeRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='ranger_eye/recordings/')),
                ('duration_seconds', models.PositiveIntegerField(default=60)),
                ('source', models.CharField(blank=True, default='ESP32-CAM stream', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
