# Generated by Django 6.0.3 on 2026-05-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranger_eye', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangerEyeSensorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('device_name', models.CharField(blank=True, default='ESP32 Sensor Node', max_length=120)),
                ('location', models.CharField(blank=True, default='Protected Plant Zone', max_length=255)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=40)),
                ('soil_value', models.IntegerField(blank=True, null=True)),
                ('sound_state', models.IntegerField(blank=True, null=True)),
                ('movement_score', models.FloatField(blank=True, null=True)),
                ('accel_x', models.FloatField(blank=True, null=True)),
                ('accel_y', models.FloatField(blank=True, null=True)),
                ('accel_z', models.FloatField(blank=True, null=True)),
                ('wifi_rssi', models.IntegerField(blank=True, null=True)),
                ('mpu_ready', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-last_seen_at', '-updated_at'),
            },
        ),
    ]
