# Generated by Django 6.0.3 on 2026-05-12 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_esp32_defaults'),
        ('secure_files', '0002_securefile_category_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_mode', models.CharField(choices=[('phone', 'Phone camera'), ('esp32', 'ESP32 camera')], default='esp32', max_length=24)),
                ('camera_source', models.CharField(blank=True, default='RE-CAM-01', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('alert', 'Alert generated'), ('no_detection', 'No detection'), ('processing_failed', 'Processing failed')], default='recorded', max_length=32)),
                ('video_filename', models.CharField(blank=True, default='', max_length=255)),
                ('video_duration', models.CharField(blank=True, default='', max_length=32)),
                ('details', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_clips', to='monitoring.violationalert')),
                ('evidence_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_clips', to='secure_files.securefile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clips', to='monitoring.monitorsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_clips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-recorded_at', '-id'),
            },
        ),
    ]
