# Generated by Django 6.0.3 on 2026-05-04 01:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_id', models.CharField(max_length=100, unique=True)),
                ('name', models.JSONField(help_text='Multilingual badge name {en, ms, zh}')),
                ('description', models.JSONField(help_text='Multilingual description {en, ms, zh}')),
                ('icon_url', models.URLField(help_text='Badge icon image URL')),
                ('requirement', models.CharField(help_text='Human-readable requirement', max_length=500)),
            ],
            options={
                'ordering': ['badge_id'],
            },
        ),
        migrations.CreateModel(
            name='ARSimulationQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('question_text', models.JSONField(help_text='Multilingual question {en, ms, zh}')),
                ('question_image_url', models.URLField(blank=True, help_text='Optional image with question', null=True)),
                ('options', models.JSONField(help_text='Multilingual options array {en: [], ms: [], zh: []}')),
                ('correct_option_index', models.PositiveIntegerField(help_text='Index of correct option (0-3)')),
                ('correct_explanation', models.JSONField(help_text='Multilingual feedback on correct answer {en, ms, zh}')),
                ('incorrect_explanation', models.JSONField(help_text='Multilingual feedback on wrong answer {en, ms, zh}')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('time_limit_seconds', models.PositiveIntegerField(default=30, help_text='Time to answer')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scenario', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ARQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer_index', models.PositiveIntegerField(help_text="Index of user's selected option")),
                ('is_correct', models.BooleanField()),
                ('time_taken_seconds', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_quiz_attempts', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_training.arsimulationquiz')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='ARSimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique scenario code', max_length=100, unique=True)),
                ('title', models.JSONField(help_text='Multilingual title {en, ms, zh}')),
                ('description', models.JSONField(help_text='Detailed scenario description')),
                ('learning_objectives', models.JSONField(help_text='What trainee learns: array of objectives in {en, ms, zh}')),
                ('scenario_type', models.CharField(choices=[('biodiversity', 'Forest Biodiversity Training'), ('wildlife', 'Wildlife Safety & Encounter'), ('ecotourism', 'Eco-tourism Management'), ('conservation', 'Conservation & Restoration'), ('guiding', 'Professional Guide Skills')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=8, help_text='Quick 5-10 min browse experience')),
                ('thumbnail', models.URLField(blank=True, help_text='Scenario thumbnail for list view', null=True)),
                ('immersion_type', models.CharField(choices=[('guided_tour', 'Guided Tour - Linear narrative'), ('exploration', 'Free Exploration - Self-paced'), ('simulation', 'Interactive Simulation - Decision-making')], default='guided_tour', max_length=20)),
                ('initial_panorama_url', models.URLField(help_text='Starting 360° panorama image')),
                ('intro_audio_url', models.URLField(blank=True, help_text='Optional intro audio narration', null=True)),
                ('intro_audio_duration_seconds', models.PositiveIntegerField(default=0)),
                ('park_location', models.CharField(blank=True, help_text='Which park/area', max_length=200)),
                ('weather_best', models.CharField(blank=True, help_text='Best time/weather to visit', max_length=100)),
                ('safety_warning', models.JSONField(blank=True, help_text='Optional warnings {en, ms, zh}', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['scenario_type', 'is_published'], name='ar_training_scenari_ccad44_idx'), models.Index(fields=['difficulty'], name='ar_training_difficu_9430ca_idx'), models.Index(fields=['is_published', 'order'], name='ar_training_is_publ_18b7a4_idx')],
            },
        ),
        migrations.AddField(
            model_name='arsimulationquiz',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='ar_training.arsimulationscenario'),
        ),
        migrations.CreateModel(
            name='AR360Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Location/environment name', max_length=200)),
                ('description', models.JSONField(help_text='Context description {en, ms, zh}')),
                ('panorama_url', models.URLField(help_text='360° panoramic image (equirectangular, 1200x600px min)')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail for preview', null=True)),
                ('ambient_audio_url', models.URLField(blank=True, help_text='Background nature sounds', null=True)),
                ('ambient_audio_duration_seconds', models.PositiveIntegerField(default=0)),
                ('initial_yaw', models.FloatField(default=0, help_text='Initial camera rotation (degrees)')),
                ('initial_pitch', models.FloatField(default=0, help_text='Initial camera pitch (degrees)')),
                ('order', models.PositiveIntegerField(default=1, help_text='Tour sequence')),
                ('is_key_view', models.BooleanField(default=False, help_text='Main observation point')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='ar_training.arsimulationscenario')),
            ],
            options={
                'ordering': ['scenario', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ARTrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panoramas_visited', models.JSONField(default=list, help_text='List of panorama IDs visited')),
                ('hotspots_discovered', models.JSONField(default=list, help_text='List of hotspot IDs discovered')),
                ('quizzes_completed', models.JSONField(default=list, help_text='Quiz results')),
                ('completion_percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_completed', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_training.arsimulationscenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ARTrainingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scenarios_completed', models.PositiveIntegerField(default=0)),
                ('total_scenarios_attempted', models.PositiveIntegerField(default=0)),
                ('total_hotspots_discovered', models.PositiveIntegerField(default=0)),
                ('total_panoramas_visited', models.PositiveIntegerField(default=0)),
                ('total_quiz_attempts', models.PositiveIntegerField(default=0)),
                ('average_quiz_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_training_minutes', models.PositiveIntegerField(default=0)),
                ('current_streak_days', models.PositiveIntegerField(default=0)),
                ('longest_streak_days', models.PositiveIntegerField(default=0)),
                ('last_trained_date', models.DateField(blank=True, null=True)),
                ('total_badges_earned', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ar_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AR Training Statistics',
            },
        ),
        migrations.CreateModel(
            name='ARUserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_training.arbadge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='arsimulationquiz',
            unique_together={('scenario', 'question_id')},
        ),
        migrations.CreateModel(
            name='ARScenarioSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Order in tour')),
                ('narration_text', models.JSONField(help_text='What guide explains {en, ms, zh}')),
                ('narration_audio_url', models.URLField(blank=True, null=True)),
                ('narration_duration_seconds', models.PositiveIntegerField(default=0)),
                ('recommended_time_seconds', models.PositiveIntegerField(default=30, help_text='How long to spend here')),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_training.ar360panorama')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='ar_training.arsimulationscenario')),
            ],
            options={
                'ordering': ['scenario', 'step_number'],
                'unique_together': {('scenario', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='ARInteractiveHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_id', models.CharField(help_text='Unique identifier', max_length=100)),
                ('title', models.JSONField(help_text='Multilingual title {en, ms, zh}')),
                ('position_yaw', models.FloatField(help_text='Horizontal angle (0-360 degrees)')),
                ('position_pitch', models.FloatField(help_text='Vertical angle (-90 to 90 degrees)')),
                ('interaction_type', models.CharField(choices=[('info_card', 'Information Card'), ('question', 'Quiz Question'), ('audio_narration', 'Audio Narration'), ('animation_trigger', 'Animation Trigger'), ('3d_object', '3D Object Overlay'), ('decision_point', 'Decision Point')], max_length=20)),
                ('content', models.JSONField(help_text='\n        Flexible content based on type:\n        {\n            "title": "Display title",\n            "subtitle": "Optional subtitle",\n            "description": {"en": "", "ms": "", "zh": ""},\n            "image_url": "Optional image",\n            "audio_url": "Optional audio narration",\n            "audio_duration_seconds": 0,\n            "keywords": ["tag1", "tag2"],\n            "details": "Rich HTML content"\n        }\n    ')),
                ('color_hint', models.CharField(default='#FF6B6B', help_text='Highlight color for marker', max_length=7)),
                ('icon_type', models.CharField(default='info', help_text='Icon in 3D space', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Discovery sequence')),
                ('required_visit', models.BooleanField(default=False, help_text='Must visit to complete scenario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='ar_training.ar360panorama')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_hotspots', to='ar_training.arsimulationscenario')),
            ],
            options={
                'ordering': ['panorama', 'order'],
                'indexes': [models.Index(fields=['scenario', 'required_visit'], name='ar_training_scenari_824312_idx'), models.Index(fields=['panorama', 'order'], name='ar_training_panoram_6b15cd_idx')],
                'unique_together': {('scenario', 'hotspot_id')},
            },
        ),
        migrations.AddIndex(
            model_name='ar360panorama',
            index=models.Index(fields=['scenario', 'order'], name='ar_training_scenari_6f13a1_idx'),
        ),
        migrations.AddIndex(
            model_name='artrainingprogress',
            index=models.Index(fields=['user', 'is_completed'], name='ar_training_user_id_01e54b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='artrainingprogress',
            unique_together={('user', 'scenario')},
        ),
        migrations.AlterUniqueTogether(
            name='aruserachievement',
            unique_together={('user', 'badge')},
        ),
    ]
