# Generated by Django 6.0.3 on 2026-05-04 00:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_id', models.CharField(help_text='Unique badge identifier', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Badge name', max_length=200)),
                ('description', models.JSONField(help_text='Multilingual description {en, ms, zh}')),
                ('icon', models.CharField(help_text='Icon name (Material Design)', max_length=100)),
                ('requirement', models.CharField(help_text='Human-readable requirement', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['badge_id'],
            },
        ),
        migrations.CreateModel(
            name='ARScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique scenario code (e.g., 'ar-biodiversity-101')", max_length=100, unique=True)),
                ('title', models.JSONField(help_text='Multilingual title {en, ms, zh}')),
                ('description', models.JSONField(blank=True, help_text='Multilingual description', null=True)),
                ('scenario_type', models.CharField(choices=[('forest', 'Forest Biodiversity'), ('eco', 'Eco-tourism'), ('wildlife', 'Wildlife Safety')], help_text='Type of AR scenario', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=20, help_text='Estimated training duration')),
                ('thumbnail', models.URLField(blank=True, help_text='Scenario thumbnail', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Is this scenario available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['scenario_type', 'is_published'], name='ar_training_scenari_5b634f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ARTrainingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scenarios_completed', models.PositiveIntegerField(default=0)),
                ('total_hotspots_visited', models.PositiveIntegerField(default=0)),
                ('average_quiz_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_training_hours', models.FloatField(default=0)),
                ('current_streak_days', models.PositiveIntegerField(default=0)),
                ('longest_streak_days', models.PositiveIntegerField(default=0)),
                ('last_training_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ar_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AR Training Statistics',
            },
        ),
        migrations.CreateModel(
            name='ARQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(help_text="User's answers {question_id: option_index}")),
                ('score', models.PositiveIntegerField(help_text='Number of correct answers')),
                ('total_questions', models.PositiveIntegerField(help_text='Total number of questions')),
                ('percentage', models.FloatField(help_text='Percentage score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passed', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(help_text='Time taken for quiz')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_quiz_results', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='ar_training.arscenario')),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'scenario', '-completed_at'], name='ar_training_user_id_c80b7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ARQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('question_text', models.JSONField(help_text='Multilingual question {en, ms, zh}')),
                ('options', models.JSONField(help_text='Multilingual options {en: [...], ms: [...], zh: [...]}')),
                ('correct_option', models.PositiveIntegerField(help_text='Index of correct option (0-3)')),
                ('explanation', models.JSONField(help_text='Multilingual explanation {en, ms, zh}')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='ar_training.arscenario')),
            ],
            options={
                'ordering': ['scenario', 'order'],
                'unique_together': {('scenario', 'question_id')},
            },
        ),
        migrations.CreateModel(
            name='ARHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_id', models.CharField(help_text='Unique identifier for hotspot', max_length=100)),
                ('title', models.JSONField(help_text='Multilingual hotspot title')),
                ('position_x', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('position_y', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('content', models.JSONField(help_text='\n        {\n            "species": "Species name",\n            "scientific": "Scientific name",\n            "height": "Physical dimensions",\n            "characteristics": {"en": "...", "ms": "...", "zh": "..."},\n            "ecology": {"en": "...", "ms": "...", "zh": "..."},\n            "wildlife": ["associated", "species"],\n            "safeDistance": "100+ meters",\n            "actionPlan": {"en": "...", "ms": "...", "zh": "..."}\n        }\n    ')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='ar_training.arscenario')),
            ],
            options={
                'ordering': ['scenario', 'order'],
                'unique_together': {('scenario', 'hotspot_id')},
            },
        ),
        migrations.CreateModel(
            name='AREnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Environment name (e.g., 'Tropical Rainforest')", max_length=100)),
                ('description', models.JSONField(blank=True, help_text='Multilingual environment description', null=True)),
                ('panorama_url', models.URLField(help_text='High-resolution panoramic image URL')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail image URL', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='ar_training.arscenario')),
            ],
            options={
                'ordering': ['scenario', 'order'],
                'unique_together': {('scenario', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ARTrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_hotspots', models.JSONField(default=list, help_text='List of visited hotspot IDs')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, help_text='Total time spent on this scenario')),
                ('completion_percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='ar_training.arscenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_training_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'scenario'], name='ar_training_user_id_bbf5ea_idx'), models.Index(fields=['user', 'is_completed'], name='ar_training_user_id_01e54b_idx')],
                'unique_together': {('user', 'scenario')},
            },
        ),
        migrations.CreateModel(
            name='ARUserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ar_training.arbadge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
