# Generated by Django 6.0.3 on 2026-04-14 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_progress', '0002_init_new_badge_system'),
        ('user_progress', '0009_fix_badge_corruption'),
    ]

    operations = [
    ]
