# Generated by Django 6.0.3 on 2026-04-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_pushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtoken',
            name='token',
            field=models.TextField(db_index=True),
        ),
    ]
